library(arules)
label20_r<-read.csv("/Users/yueqizhang/Documents/w5243 ads/project4/Project4_data/data/label20_yz.csv")
dellabel<-c(714,949,990,1111,1324,1374,1657,1704,2283)
label20_r<-label20_r[-dellabel,]
feature_r<-read.csv("/Users/yueqizhang/Documents/w5243 ads/project4/data/train_10cluster.csv")
delfeature<-237
feature_r<-feature_r[-delfeature,]
data_conb<-cbind(feature_r[,2:7],label20_r[,2])
colnames(data_conb)[7]<-"Topic"
data_conb[,1]<-as.factor(data_conb[,1])
data_conb[,2]<-as.factor(data_conb[,2])
data_conb[,3]<-as.factor(data_conb[,3])
data_conb[,4]<-as.factor(data_conb[,4])
data_conb[,5]<-as.factor(data_conb[,5])
data_conb[,6]<-as.factor(data_conb[,6])
data_conb[,7]<-as.factor(data_conb[,7])
data<-as(data_conb,"transactions")
rules<-apriori(data,parameter = list(support=0,confidence=0))
rulestopic1<-subset(rules,subset=rhs %in% "Topic=1")
inspect(head(rulestopic1,n=3,by="confidence"))
rulestopic2<-subset(rules,subset=rhs %in% "Topic=2")
inspect(head(rulestopic2,n=3,by="confidence"))
rulestopic3<-subset(rules,subset=rhs %in% "Topic=3")
inspect(head(rulestopic3,n=3,by="confidence"))
rulestopic4<-subset(rules,subset=rhs %in% "Topic=4")
inspect(head(rulestopic4,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=5")
inspect(head(rulestopic5,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=6")
inspect(head(rulestopic6,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=7")
inspect(head(rulestopic7,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=8")
inspect(head(rulestopic8,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=9")
inspect(head(rulestopic9,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=10")
inspect(head(rulestopic10,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=11")
inspect(head(rulestopic11,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=12")
inspect(head(rulestopic12,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=13")
inspect(head(rulestopic13,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=14")
inspect(head(rulestopic14,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=15")
inspect(head(rulestopic15,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=16")
inspect(head(rulestopic16,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=17")
inspect(head(rulestopic17,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=18")
inspect(head(rulestopic18,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=19")
inspect(head(rulestopic19,n=3,by="confidence"))
rulestopic5<-subset(rules,subset=rhs %in% "Topic=20")
inspect(head(rulestopic20,n=3,by="confidence"))


